Repository ImJaeOne/now-what-do, pull requests merged in 2025-02, with the labels that each got.

#3 feat(#1):test commit
  src/App.jsx
Labels: ✅ Test

#8 feat/#6 : RRD 작업
  package.json
  src/App.jsx
  src/pages/Detail.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/MyPage.jsx
  src/pages/Post.jsx
  src/pages/SignUp.jsx
  src/shared/Router.jsx
  yarn.lock
Labels: ✨ Feature

#12 Feat/global style
  src/style/GlobalStyle.jsx
Labels: 🎨 Html&css

#13 Feat: 회원가입 페이지 layout 생성
  src/components/signup/SignUpPage.jsx
  src/pages/SignUp.jsx
Labels: ✨ Feature

#17 Feat: 회원가입 시 Supabase 등록 로직 작성
  .env
  package.json
  src/components/signup/SignUpPage.jsx
  src/pages/SignUp.jsx
  src/supabase/client.js
  yarn.lock
Labels: ✨ Feature

#24 feat: 비밀번호 확인 로직 추가, 비밀번호 input type 변경
  src/pages/MyPage.jsx
  src/pages/SignUp.jsx
Labels: ✨ Feature

#28 Fix/login validation
  src/pages/Login.jsx
Labels: 🐞 BugFix

#29 feat : supabase posts data 연동
  src/pages/Post.jsx
  src/style/Post/Post.style.jsx
Labels: ✨ Feature

#30 Feat/header login check: 로그아웃 버튼 기능 추가 및 로그인 시 유저 닉네임 표시
  src/components/Layout/Header.jsx
  src/components/Layout/Nav.jsx
  src/style/StLayout/Header.style.jsx
Labels: ✨ Feature

#33 Feat/float button : Float버튼을 통한 페이지 이동 구현
  src/components/Layout/FloatBtn.jsx
  src/components/Layout/Header.jsx
  src/components/Layout/Layout.jsx
  src/contexts/AuthProvider.jsx
  src/pages/Login.jsx
  src/shared/Router.jsx
  src/style/StLayout/FloatBtn.Style.jsx
  src/style/StLayout/Header.style.jsx
Labels: ✨ Feature

#35 Feat: 마이페이지 내 유저 정보 수정 부분 추가
  src/contexts/AuthProvider.jsx
  src/pages/MyPage.jsx
Labels: ✨ Feature

#37 Feat/supabase card
  src/assets/다운로드.jpeg
  src/pages/Home.jsx
  src/pages/MyPage.jsx
  src/utils/dateUtils.js
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#38 feat : post페이지에서 입력한 사진 posts테이블로 업로드 성공
  src/pages/Post.jsx
Labels: ✨ Feature, 🔨 Refactor

#44 fix : 제출 안되던 부분 해결
  src/pages/Post.jsx
Labels: 🐞 BugFix

#54 Feat: 마이페이지 이미지 미리보기, 좋아요 수정, 컴포넌트 분리
  src/components/MyPage/MyInfo.jsx
  src/components/MyPage/MyPost.jsx
  src/components/MyPage/MyPostList.jsx
  src/components/common/CommentBtn.jsx
  src/pages/MyPage.jsx
  src/style/MyPage/MyInfo.style.jsx
  src/style/MyPage/MyPost.style.jsx
  src/style/MyPage/MyPostList.style.jsx
Labels: ✨ Feature

#57 feat: post페이지 파일 미리보기 추가, 파일 유효성 검사 추가, 미디어쿼리 설정
  src/pages/Post.jsx
  src/style/Post/Post.style.jsx
  src/style/StLayout/Layout.style.jsx
  src/utils/category.jsx
  src/utils/validateFile.js
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#58 Style: 회원가입, 로그인 페이지 css 통일
  src/components/SignUp/SignUpInput.jsx
  src/components/common/IconBtn.jsx
  src/pages/Login.jsx
  src/pages/SignUp.jsx
  src/style/Auth/Auth.Input.style.jsx
  src/style/Login/Login.style.jsx
  src/style/SignUp/SignUp.style.jsx
Labels: 🎨 Html&css

#61 Feat: 마이페이지 더보기 기능
  src/components/MyPage/MyInfo.jsx
  src/components/MyPage/MyPost.jsx
  src/components/MyPage/MyPostList.jsx
  src/style/MyPage/MyPost.style.jsx
  src/style/MyPage/MyPostList.style.jsx
Labels: ✨ Feature

#63 feat : 카테고리 비주얼 업데이트
  src/pages/Post.jsx
  src/style/Post/Post.style.jsx
  src/utils/category.jsx
Labels: ✨ Feature, 🎨 Html&css

#67 style : post페이지 전반적인 스타일 수정
  src/pages/Post.jsx
  src/style/Post/Post.style.jsx
Labels: 🎨 Html&css

#68 bugfix : 게시물 게시 안되는 부분 수정
  src/pages/Post.jsx
  src/style/Post/Post.style.jsx
  src/utils/category.jsx
Labels: 🐞 BugFix

#70 style : 768 반응형 추가, 이미지 파일 수정
  src/pages/post/Post.jsx
  src/pages/post/postStyle/Post.style.jsx
Labels: 🎨 Html&css
